"""
Live single-candidate scoring: the exact five-pillar model validated in
backtest/ (hand-set weights, the completed Player Skill pillar with
Pull%/FB%, no red-flag penalties — per the decision documented in
backtest/README.md), ported to score one player's HR prop for one game at
a time, rather than a historical batch/dataframe.

This module is pure Python, no pandas — it loads a small bundled JSON
snapshot (reference_data/reference_snapshot_2025.json, generated by
scripts/build_reference_snapshot.py from backtest/'s validated 2025
baselines — the most recently completed full season; see
pipeline/README.md for the 2022->2025 refresh and what it changed)
instead of depending on backtest/'s data or code at runtime, so it can be
deployed standalone the same way flatten_hr_props.py is.

Not wired to live data or deployed as an endpoint yet — this is the
scoring function itself, tested against hand-made realistic sample
candidates in test_score_candidate.py.

INPUT SCHEMA (all fields optional — missing ones fall back to neutral (50)
and are recorded in the returned `notes` list, never silently dropped):

  Identity (informational only, not scored):
    player_name, team, opp_pitcher_name

  Player skill (Pillar 1):
    barrel_pct, hard_hit_pct, avg_exit_velo, sweet_spot_pct, fb_pct,
    pull_pct, xslg, xwoba, hr_per_pa
    expected_hr                — ACCEPTED, NOT SCORED (see notes)

  Opposing pitcher (Pillar 2):
    opp_throws ("L"/"R"), opp_barrel_pct_allowed, opp_hard_hit_pct_allowed,
    opp_xslg_allowed, opp_xwoba_allowed, opp_hr_per_9, opp_k_per_9
    opp_fb_pct_allowed, opp_avg_exit_velo_allowed, opp_xera,
    pitch_type_tendencies       — ACCEPTED, NOT SCORED (see notes)

  Matchup context:
    batter_stand ("L"/"R")      — combined with opp_throws for platoon

  Environment (Pillar 3):
    home_team (3-letter code, looked up against the bundled park factor
    table), wind_speed_mph, wind_description (free text, e.g. "Out To LF"),
    temp_f, roof_status ("open"/"closed"/"dome"/"outdoor" — closed/dome
    forces neutral wind)

  Opportunity (Pillar 4):
    batting_order_slot (1-9)
    projected_pa                — ACCEPTED, NOT SCORED, KNOWN LIVE-SOURCING GAP
    opp_bullpen_hr_per_pa, opp_bullpen_hard_hit_pct, opp_bullpen_k_pct
                                 — KNOWN LIVE-SOURCING GAP (see notes)

  Odds:
    odds (American, e.g. 450 for +300) — drives passes_odds_filter

KNOWN GAPS — every "ACCEPTED, NOT SCORED" or "KNOWN LIVE-SOURCING GAP"
field above generates an explicit entry in the returned `notes` list
whenever it's provided or missing, so a caller never has to guess whether
an input actually influenced the score.
"""
import bisect
import json
from pathlib import Path

_SNAPSHOT_PATH = Path(__file__).resolve().parent / "reference_data" / "reference_snapshot_2025.json"
with open(_SNAPSHOT_PATH) as _f:
    _SNAPSHOT = json.load(_f)

CONFIG = _SNAPSHOT["config"]
NEUTRAL = 50.0


def percentile_lookup(value, sorted_reference: list) -> float:
    """
    % of the reference population at or below `value`, 0-100, matching
    backtest/scoring/normalize.py's np.searchsorted(..., side="left") exactly
    (bisect.bisect_left is the pure-Python equivalent). None -> None (caller
    decides the neutral fallback), never silently coerced to 0.
    """
    if value is None:
        return None
    n = len(sorted_reference)
    if n == 0:
        return None
    idx = bisect.bisect_left(sorted_reference, value)
    return idx / n * 100


def _neutral_if_none(value, default=NEUTRAL):
    return default if value is None else value


def _wind_direction_multiplier(desc) -> float:
    """Ported verbatim from backtest/scoring/features.py for consistency —
    duplicated rather than imported because this module has zero runtime
    dependency on backtest/ by design."""
    if desc is None:
        return 0.0
    d = str(desc).lower()
    if "out" in d:
        return 1.0
    if "in" in d:
        return -1.0
    return 0.0  # cross-wind ("L To R" / "R To L") treated as neutral, same as backtest


def _mean(values: list) -> float:
    values = [v for v in values if v is not None]
    return sum(values) / len(values) if values else None


def score_skill(c: dict, notes: list) -> dict:
    cfg = CONFIG["skill"]
    scales = _SNAPSHOT["batter_scales"]
    bb_scales = _SNAPSHOT["batted_ball_scales"]

    contact_quality_raw = [
        percentile_lookup(c.get("avg_exit_velo"), scales["avg_exit_velo"]),
        percentile_lookup(c.get("hard_hit_pct"), scales["hard_hit_pct"]),
        percentile_lookup(c.get("sweet_spot_pct"), scales["sweet_spot_pct"]),
        percentile_lookup(c.get("fb_pct"), bb_scales["fb_pct"]),
        percentile_lookup(c.get("pull_pct"), bb_scales["pull_pct"]),
    ]
    contact_quality = _neutral_if_none(_mean(contact_quality_raw))

    power_production_raw = [
        percentile_lookup(c.get("barrel_pct"), scales["barrel_pct"]),
        percentile_lookup(c.get("xslg"), scales["xslg"]),
        percentile_lookup(c.get("xwoba"), scales["xwoba"]),
    ]
    power_production = _neutral_if_none(_mean(power_production_raw))

    track_record = _neutral_if_none(percentile_lookup(c.get("hr_per_pa"), scales["hr_per_pa"]))

    if c.get("expected_hr") is not None:
        notes.append(
            "expected_hr was provided but is not a separate scoring input — matches backtest's "
            "documented decision that 'expected home runs' isn't a standard published stat; "
            "barrel%/xSLG already serve as the proxy in Power Production."
        )

    score = (
        cfg["contact_quality_weight"] * contact_quality
        + cfg["power_production_weight"] * power_production
        + cfg["track_record_weight"] * track_record
    )
    return {
        "score": round(score, 1),
        "components": {
            "contact_quality": round(contact_quality, 1),
            "power_production": round(power_production, 1),
            "track_record": round(track_record, 1),
        },
    }


def score_matchup(c: dict, notes: list) -> dict:
    cfg = CONFIG["matchup"]
    scales = _SNAPSHOT["pitcher_scales"]

    contact_allowed_raw = [
        percentile_lookup(c.get("opp_hard_hit_pct_allowed"), scales["hard_hit_pct_allowed"]),
        percentile_lookup(c.get("opp_barrel_pct_allowed"), scales["barrel_pct_allowed"]),
        percentile_lookup(c.get("opp_xslg_allowed"), scales["xslg_allowed"]),
        percentile_lookup(c.get("opp_xwoba_allowed"), scales["xwoba_allowed"]),
    ]
    contact_allowed = _neutral_if_none(_mean(contact_allowed_raw))

    hr9_pct = percentile_lookup(c.get("opp_hr_per_9"), scales["hr_per_9"])
    k9_pct = percentile_lookup(c.get("opp_k_per_9"), scales["k_per_9"])
    k9_pct_inverted = None if k9_pct is None else 100 - k9_pct
    rate_outcome = _neutral_if_none(_mean([hr9_pct, k9_pct_inverted]))

    pitcher_quality = cfg["contact_allowed_weight"] * contact_allowed + cfg["rate_outcome_weight"] * rate_outcome

    batter_stand = c.get("batter_stand")
    opp_throws = c.get("opp_throws")
    platoon_adj = 0.0
    platoon_note = "unknown (batter_stand or opp_throws missing) — no platoon adjustment applied"
    if batter_stand is not None and opp_throws is not None:
        is_opposite = batter_stand != opp_throws
        platoon_adj = _SNAPSHOT["platoon"]["bonus_opposite"] if is_opposite else _SNAPSHOT["platoon"]["bonus_same"]
        platoon_note = f"{'opposite' if is_opposite else 'same'}-handed ({batter_stand} vs {opp_throws})"

    unused_matchup_fields = {
        "opp_fb_pct_allowed": "never part of the validated matchup pillar — pitcher fly-ball-rate-allowed "
                               "is a documented open gap in backtest/README.md, not yet validated for scoring.",
        "opp_avg_exit_velo_allowed": "never part of the validated matchup pillar (hard-hit%/barrel%/xSLG/"
                                      "xwOBA allowed are the validated contact-quality inputs, not raw exit velo).",
        "opp_xera": "never part of the validated matchup pillar.",
        "pitch_type_tendencies": "never part of the validated model at all — no pillar currently scores this.",
    }
    for field, reason in unused_matchup_fields.items():
        if c.get(field) is not None:
            notes.append(f"{field} was provided but is not used — {reason}")

    score = (pitcher_quality + platoon_adj)
    score = max(0.0, min(100.0, score))
    return {
        "score": round(score, 1),
        "components": {
            "contact_allowed": round(contact_allowed, 1),
            "rate_outcome": round(rate_outcome, 1),
            "platoon_adjustment": round(platoon_adj, 2),
            "platoon_note": platoon_note,
        },
    }


def score_environment(c: dict, notes: list) -> dict:
    cfg = CONFIG["environment"]

    home_team = c.get("home_team")
    park_factor = _SNAPSHOT["park_factor_by_team"].get(home_team) if home_team else None
    if home_team and park_factor is None:
        notes.append(f"home_team {home_team!r} not found in the {_SNAPSHOT['season']} park factor reference — using neutral (50).")
    pf_min, pf_max = _SNAPSHOT["park_factor_min"], _SNAPSHOT["park_factor_max"]
    if park_factor is not None:
        park_score = (park_factor - pf_min) / (pf_max - pf_min) * 100
        park_score = max(0.0, min(100.0, park_score))
    else:
        park_score = NEUTRAL

    roof_status = (c.get("roof_status") or "").lower()
    indoor = roof_status in ("closed", "dome")
    wind_speed = 0.0 if indoor else (c.get("wind_speed_mph") or 0.0)
    direction_mult = 0.0 if indoor else _wind_direction_multiplier(c.get("wind_description"))
    ceiling = cfg["wind_speed_ceiling_mph"]
    wind_component = max(-100.0, min(100.0, (wind_speed / ceiling * 100))) * direction_mult
    wind_score = max(0.0, min(100.0, 50 + wind_component / 2))

    temp_f = c.get("temp_f")
    if temp_f is not None:
        t_min, t_max = _SNAPSHOT["temp_min_f"], _SNAPSHOT["temp_max_f"]
        temp_score = max(0.0, min(100.0, (temp_f - t_min) / (t_max - t_min) * 100))
    else:
        temp_score = NEUTRAL
        notes.append("temp_f not provided — using neutral (50) for the weather component.")

    weather_score = (wind_score + temp_score) / 2
    score = cfg["park_weight"] * park_score + cfg["weather_weight"] * weather_score
    return {
        "score": round(score, 1),
        "components": {
            "park": round(park_score, 1),
            "weather": round(weather_score, 1),
            "wind": round(wind_score, 1),
            "temp": round(temp_score, 1),
            "park_factor_hr": park_factor,
        },
    }


def score_opportunity(c: dict, notes: list) -> dict:
    cfg = CONFIG["opportunity"]
    scales = _SNAPSHOT["bullpen_scales"]

    slot = c.get("batting_order_slot")
    order_score = _SNAPSHOT["batting_order_curve"].get(str(int(slot))) if slot is not None else None
    order_score = _neutral_if_none(order_score)
    if slot is None:
        notes.append("batting_order_slot not provided — using neutral (50) for the opportunity pillar's order component.")

    if c.get("projected_pa") is not None:
        notes.append(
            "projected_pa was provided but is not a scoring input in the validated model — "
            "opportunity is scored via batting_order_slot mapped through an empirically-calibrated "
            "PA curve, not a projected-PA figure directly. This is also a known gap for live sourcing "
            "(see backtest/README.md: 'projected PA is still not a real pre-game input')."
        )

    bullpen_inputs = [c.get("opp_bullpen_hr_per_pa"), c.get("opp_bullpen_hard_hit_pct"), c.get("opp_bullpen_k_pct")]
    if all(v is None for v in bullpen_inputs):
        notes.append(
            "No opposing bullpen metrics provided — using neutral (50). KNOWN GAP: bullpen quality IS "
            "computable with the same methodology validated in backtest/ (scripts/fetch_bullpen_quality.py), "
            "but that's only been run for 2021-2023 — a current-season bullpen reference table hasn't been "
            "built yet, so this can't be sourced live until that's done."
        )

    hr_pa_pct = percentile_lookup(c.get("opp_bullpen_hr_per_pa"), scales["bullpen_hr_per_pa"])
    hard_hit_pct = percentile_lookup(c.get("opp_bullpen_hard_hit_pct"), scales["bullpen_hard_hit_pct"])
    k_pct = percentile_lookup(c.get("opp_bullpen_k_pct"), scales["bullpen_k_pct"])
    k_pct_inverted = None if k_pct is None else 100 - k_pct
    bullpen_score = _neutral_if_none(_mean([hr_pa_pct, hard_hit_pct, k_pct_inverted]))

    score = cfg["batting_order_weight"] * order_score + cfg["bullpen_weight"] * bullpen_score
    return {
        "score": round(score, 1),
        "components": {
            "batting_order": round(order_score, 1),
            "bullpen": round(bullpen_score, 1),
        },
    }


# Tier label per star count — kept as one mapping, not two independent
# scales. An earlier version derived score_tier from fixed thresholds
# (80/65/50/35, matching the existing deployed hr_score.py's Elite/Strong/
# Moderate/Weak/Poor convention) while star_rating used quintile boundaries
# from the real score distribution — those two scales disagreed often
# enough in testing (a real candidate landed 5 stars *and* "Moderate") that
# a later AI-writing step could end up saying "Moderate pick, ★★★★★" in
# the same breath. Tier now always agrees with stars by construction.
_TIER_BY_STARS = {5: "Elite", 4: "Strong", 3: "Moderate", 2: "Weak", 1: "Poor"}


def _star_rating(final_score: float) -> int:
    """1-5 stars, from quintile boundaries of the validated 2023 full-season
    backtest's actual final_score distribution — evidence-based cut points,
    not arbitrary round numbers."""
    boundaries = _SNAPSHOT["star_rating_boundaries"]
    return bisect.bisect_right(boundaries, final_score) + 1


def _score_tier(star_rating: int) -> str:
    return _TIER_BY_STARS[star_rating]


MIN_ODDS_FOR_FILTER = 300


def score_candidate(candidate: dict) -> dict:
    """
    Scores one player's HR prop for one game. See module docstring for the
    full input schema and known gaps. Never raises on missing optional
    fields — falls back to neutral (50) and records why in `notes`,
    matching the same "don't penalize on missing info" philosophy
    validated throughout backtest/.
    """
    notes = []

    skill = score_skill(candidate, notes)
    matchup = score_matchup(candidate, notes)
    environment = score_environment(candidate, notes)
    opportunity = score_opportunity(candidate, notes)

    w = CONFIG["pillar_weights"]
    final_score = (
        w["skill"] * skill["score"]
        + w["matchup"] * matchup["score"]
        + w["environment"] * environment["score"]
        + w["opportunity"] * opportunity["score"]
    )
    final_score = round(final_score, 1)

    odds = candidate.get("odds")
    passes_odds_filter = odds is not None and odds >= MIN_ODDS_FOR_FILTER
    if odds is None:
        notes.append("odds not provided — passes_odds_filter defaulted to False.")

    return {
        "player_name": candidate.get("player_name"),
        "team": candidate.get("team"),
        "opp_pitcher_name": candidate.get("opp_pitcher_name"),
        "odds": odds,
        "passes_odds_filter": passes_odds_filter,
        "pillars": {
            "skill": skill,
            "matchup": matchup,
            "environment": environment,
            "opportunity": opportunity,
        },
        "pillar_weights": w,
        "final_score": final_score,
        "star_rating": (stars := _star_rating(final_score)),
        "score_tier": _score_tier(stars),
        "notes": notes,
    }
